class SolverEvent(object):
    MISSING_SRC = "missing-source"
    BUILD_START = "build-start"
    BUILD_END = "build-end"
    BUILD_FAILED = "build-failed"
    SOLVE_START = "solve-start"
    SOLVE_END = "solve-end"
    SOLVE_ATTEMPTED = "solved-attempted"
    SOLVE_SUCCEEDED = "solve-succeeded"
    SOLVE_ERRED = "solve-erred"
    SOLVE_FAILED = "solve-failed"
    OUTPUT_SAVED = "output-saved"
    TIMING_START = "timing-start"
    TIMING_SKIPPED = "timing-skipped"
    TIMING_END = "timing-end"
    TIMING_FAILED = "timing-failed"
    TERMINATE = "terminate"
